# Generated by Django 2.2.3 on 2019-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190807_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
