# Generated by Django 2.2.3 on 2019-08-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20190807_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workoutdegree',
            field=models.FloatField(default=0),
        ),
    ]
