# Generated by Django 2.2.3 on 2019-08-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymodel',
            name='basal_metabolism',
        ),
        migrations.AddField(
            model_name='bodymodel',
            name='cutting_calorie',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bodymodel',
            name='increasing_calorie',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bodymodel',
            name='maintenance_calorie',
            field=models.FloatField(default=0),
        ),
    ]
