# Generated by Django 2.2.3 on 2019-08-09 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleapp', '0002_auto_20190807_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymodel',
            name='muscle_mass',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bodymodel',
            name='percent_body_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bodymodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='dietmodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='workoutmodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
    ]
