# Generated by Django 2.2.3 on 2019-08-10 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleapp', '0003_auto_20190809_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 10)),
        ),
        migrations.AlterField(
            model_name='dietmodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 10)),
        ),
        migrations.AlterField(
            model_name='workoutmodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 10)),
        ),
    ]
